INSERT INTO COUNTRIES (ID, NAME) VALUES (1, 'UK');
INSERT INTO COUNTRIES (ID, NAME) VALUES (2, 'India');
INSERT INTO COUNTRIES (ID, NAME) VALUES (3, 'UAE');


INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (1, 'Dubai', 3);
INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (2, 'London', 1);
INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (3, 'Belfast', 1);
INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (4, 'Chennai', 2);
INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (5, 'Bangalore', 2);
INSERT INTO CITIES (ID, NAME, COUNTRY_ID) VALUES (6, 'Cochin', 2);


INSERT INTO DELIVERY_APPS (ID, NAME, IS_IOS_AVAILABLE, IS_ANDRIOD_OS_AVAILABLE) VALUES (1, 'Zomato', 'true', 'true');
INSERT INTO DELIVERY_APPS (ID, NAME, IS_IOS_AVAILABLE, IS_ANDRIOD_OS_AVAILABLE) VALUES (2, 'Swiggy', 'true', 'false');
INSERT INTO DELIVERY_APPS (ID, NAME, IS_IOS_AVAILABLE, IS_ANDRIOD_OS_AVAILABLE) VALUES (3, 'Uber', 'true', 'true');
INSERT INTO DELIVERY_APPS (ID, NAME, IS_IOS_AVAILABLE, IS_ANDRIOD_OS_AVAILABLE) VALUES (4, 'Deliveroo', 'true', 'true');



INSERT INTO RESTAURANTS (ID, NAME, CITY_ID, DELIVERY_APP_ID) VALUES (1, 'Indian Coffee House', 6, 1);
INSERT INTO RESTAURANTS (ID, NAME, CITY_ID, DELIVERY_APP_ID) VALUES (2, 'Gazebo', 1, 1);
INSERT INTO RESTAURANTS (ID, NAME, CITY_ID, DELIVERY_APP_ID) VALUES (3, 'Tasties', 2, 4);
INSERT INTO RESTAURANTS (ID, NAME, CITY_ID, DELIVERY_APP_ID) VALUES (4, 'Aryaas', 6, 3);
INSERT INTO RESTAURANTS (ID, NAME, CITY_ID, DELIVERY_APP_ID) VALUES (5, 'Pizza hut', 2, 3);